# Generated by Django 5.2.4 on 2025-07-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title/heading', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Slide subtitle/description')),
                ('image', models.ImageField(help_text='Background image for the slide', upload_to='homepage_slides/')),
                ('button_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=100)),
                ('button_link', models.URLField(blank=True, help_text='Call-to-action button link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Slide',
                'verbose_name_plural': 'Homepage Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
