# Generated by Django 5.2.4 on 2025-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepageslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='button_link',
            field=models.CharField(blank=True, choices=[('/', 'Home'), ('/about', 'About Us'), ('/services', 'Our Services'), ('/team', 'Our Team'), ('/media-coverage', 'Media Coverage'), ('/success-stories', 'Success Stories'), ('/blog', 'Blog'), ('/contact', 'Contact Us'), ('/book-consultation', 'Book Consultation'), ('', 'No Link (Display Only)')], help_text='Select a page to link to, or leave empty for display-only slides', max_length=100),
        ),
    ]
