# Generated by Django 5.2.4 on 2025-08-02 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactinfo_socialmedialink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacoverage',
            options={'ordering': ['-display_priority', '-date'], 'verbose_name': 'Media Coverage', 'verbose_name_plural': 'Media Coverage'},
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='display_priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first'),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='display_size',
            field=models.CharField(choices=[('small', 'Small (1x1)'), ('medium', 'Medium (2x1)'), ('large', 'Large (2x2)'), ('wide', 'Wide (2x1)')], default='small', max_length=10),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link to external article/video'),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured section'),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='media_type',
            field=models.CharField(choices=[('news', 'News Article'), ('interview', 'Interview'), ('award', 'Award/Recognition'), ('research', 'Research Publication'), ('conference', 'Conference/Speaking'), ('testimonial', 'Patient Testimonial'), ('achievement', 'Achievement'), ('social_impact', 'Social Impact'), ('technology', 'Technology Innovation'), ('statistics', 'Success Statistics')], default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='source',
            field=models.CharField(blank=True, help_text='Media source (e.g., Times of India, NDTV)', max_length=100),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='description',
            field=models.TextField(help_text='Brief description with character limit for display'),
        ),
    ]
