# Generated by Django 5.2.4 on 2025-11-06 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_mediacoverage_options_mediacoverage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualifications', models.CharField(blank=True, max_length=300)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Administrative Staff'), ('technician', 'Technician'), ('support', 'Support Staff'), ('management', 'Management')], default='support', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='degrees',
            field=models.CharField(blank=True, help_text='Medical degrees and certifications', max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_consultant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='media_type',
            field=models.CharField(choices=[('news', 'News Article'), ('interview', 'Interview'), ('award', 'Award/Recognition'), ('research', 'Research Publication'), ('conference', 'Conference/Speaking'), ('testimonial', 'Patient Testimonial'), ('achievement', 'Achievement'), ('social_impact', 'Social Impact'), ('technology', 'Technology Innovation'), ('statistics', 'Success Statistics'), ('academic', 'Academic Excellence')], default='news', max_length=20),
        ),
    ]
